name: Run Crawler - Update data # 워크플로우 이름 지정

on:
  schedule:
    - cron:  '*/240 * * * *' # 주기적으로 실행하기 위한 스케줄링 - cron 설정

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Crawler with python
      run: |
        python "crawler.py"
    - name: Commits
      run: |
        git config --local user.email "dev_kwon97@naver.com"
        git config --local user.name "devkwon97" # 커밋에 포함될 이름
        git add news.json
        git commit -m "Auto commit" # 커밋 메세지
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $ 
